name: Crawl & Build Data
on:
  schedule:
    - cron: '0 9,15,21 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Run crawler
      run: python scripts/autocrawl.py
    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Update data" || echo "No changes"
        git push
