name: Fix repo structure (safe, no workflow move)

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - run: mkdir -p assets data scripts public .github/workflows

      - name: Move files (skip workflows)
        shell: bash
        run: |
          set -euo pipefail
          move_if(){ [ -f "$1" ] && { mkdir -p "$(dirname "$2")"; git mv -f "$1" "$2" 2>/dev/null || { mv -f "$1" "$2"; git add -A; }; echo "OK $1 -> $2"; } || echo "SKIP $1"; }
          move_if style.css   assets/style.css
          move_if app.js      assets/app.js
          move_if seed.json   data/seed.json
          move_if autocrawl.py scripts/autocrawl.py
          move_if sources.csv  scripts/sources.csv
          move_if ads.txt      public/ads.txt
          [ -f readmee ] && (git rm -f readmee || rm -f readmee)

      - name: Commit & Push
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: fix repo structure (auto)"
          add: "."
          default_author: github_actions
